const entitiesList = document.getElementById('entitiesList');
const searchBar = document.getElementById('searchBar');

const entities = [
    { "number": 200, "orga": "France" },
    { "number": 1, "orga": "Afghanistan" },
    { "number": 201, "orga": "Afghanistan" },
    { "number": 2, "orga": "Afrique-du-Sud" },
    { "number": 202, "orga": "Afrique-du-Sud" },
    { "number": 3, "orga": "Albanie" },
    { "number": 203, "orga": "Albanie" },
    { "number": 4, "orga": "Algérie" },
    { "number": 204, "orga": "Algérie" },
    { "number": 5, "orga": "Allemagne" },
    { "number": 205, "orga": "Allemagne" },
    { "number": 6, "orga": "U.S.A." },
    { "number": 206, "orga": "U.S.A." },
    { "number": 7, "orga": "Égypte" },
    { "number": 207, "orga": "Égypte" },
    { "number": 8, "orga": "Arabie Saoudite" },
    { "number": 208, "orga": "Arabie Saoudite" },
    { "number": 9, "orga": "Argentine" },
    { "number": 209, "orga": "Argentine" },
    { "number": 10, "orga": "Australie" },
    { "number": 210, "orga": "Australie" },
    { "number": 11, "orga": "Autriche" },
    { "number": 211, "orga": "Autriche" },
    { "number": 12, "orga": "Belgique" },
    { "number": 212, "orga": "Belgique" },
    { "number": 13, "orga": "Myanmar" },
    { "number": 213, "orga": "Myanmar" },
    { "number": 14, "orga": "Bolivie" },
    { "number": 214, "orga": "Bolivie" },
    { "number": 15, "orga": "Bhoutan" },
    { "number": 215, "orga": "Bhoutan" },
    { "number": 16, "orga": "Brésil" },
    { "number": 216, "orga": "Brésil" },
    { "number": 17, "orga": "Bulgarie" },
    { "number": 217, "orga": "Bulgarie" },
    { "number": 18, "orga": "Burundi" },
    { "number": 218, "orga": "Burundi" },
    { "number": 19, "orga": "Cambodge" },
    { "number": 219, "orga": "Cambodge" },
    { "number": 20, "orga": "Cameroun" },
    { "number": 220, "orga": "Cameroun" },
    { "number": 21, "orga": "Canada" },
    { "number": 221, "orga": "Canada" },
    { "number": 22, "orga": "Centrafrique" },
    { "number": 222, "orga": "Centrafrique" },
    { "number": 23, "orga": "Sri Lanka" },
    { "number": 223, "orga": "Sri Lanka" },
    { "number": 24, "orga": "Chili" },
    { "number": 224, "orga": "Chili" },
    { "number": 25, "orga": "Taïwan (obsolète)" },
    { "number": 225, "orga": "Taïwan (obsolète)" },
    { "number": 26, "orga": "Chine (Rép. Populaire)" },
    { "number": 226, "orga": "Chine (Rép. Populaire)" },
    { "number": 27, "orga": "Chypre" },
    { "number": 227, "orga": "Chypre" },
    { "number": 28, "orga": "Colombie" },
    { "number": 228, "orga": "Colombie" },
    { "number": 29, "orga": "Congo Brazzaville" },
    { "number": 229, "orga": "Congo Brazzaville" },
    { "number": 30, "orga": "Congo Kinshasa" },
    { "number": 230, "orga": "Congo Kinshasa" },
    { "number": 31, "orga": "Corée-du-Sud" },
    { "number": 231, "orga": "Corée-du-Sud" },
    { "number": 32, "orga": "Costa Rica" },
    { "number": 232, "orga": "Costa Rica" },
    { "number": 33, "orga": "Côte-d'Ivoire" },
    { "number": 233, "orga": "Côte-d'Ivoire" },
    { "number": 34, "orga": "Cuba" },
    { "number": 234, "orga": "Cuba" },
    { "number": 35, "orga": "Bénin" },
    { "number": 235, "orga": "Bénin" },
    { "number": 36, "orga": "Danemark" },
    { "number": 236, "orga": "Danemark" },
    { "number": 37, "orga": "République Dominicaine" },
    { "number": 237, "orga": "République Dominicaine" },
    { "number": 38, "orga": "El Salvador" },
    { "number": 238, "orga": "El Salvador" },
    { "number": 39, "orga": "Équateur" },
    { "number": 239, "orga": "Équateur" },
    { "number": 40, "orga": "Espagne" },
    { "number": 240, "orga": "Espagne" },
    { "number": 41, "orga": "Éthiopie" },
    { "number": 241, "orga": "Éthiopie" },
    { "number": 42, "orga": "Finlande" },
    { "number": 242, "orga": "Finlande" },
    { "number": 43, "orga": "Gabon" },
    { "number": 243, "orga": "Gabon" },
    { "number": 44, "orga": "Ghana" },
    { "number": 244, "orga": "Ghana" },
    { "number": 45, "orga": "Grande-Bretagne" },
    { "number": 245, "orga": "Grande-Bretagne" },
    { "number": 46, "orga": "Grèce" },
    { "number": 246, "orga": "Grèce" },
    { "number": 47, "orga": "Guatemala" },
    { "number": 247, "orga": "Guatemala" },
    { "number": 48, "orga": "Guinée" },
    { "number": 248, "orga": "Guinée" },
    { "number": 49, "orga": "Haïti" },
    { "number": 249, "orga": "Haïti" },
    { "number": 50, "orga": "Burkina Faso" },
    { "number": 250, "orga": "Burkina Faso" },
    { "number": 51, "orga": "Honduras" },
    { "number": 251, "orga": "Honduras" },
    { "number": 52, "orga": "Hongrie" },
    { "number": 252, "orga": "Hongrie" },
    { "number": 53, "orga": "Inde" },
    { "number": 253, "orga": "Inde" },
    { "number": 54, "orga": "Indonésie" },
    { "number": 254, "orga": "Indonésie" },
    { "number": 55, "orga": "Irak (représentation à l'UNESCO. Voir aussi 176 ou 376)" },
    { "number": 255, "orga": "Irak (représentation à l'UNESCO. Voir aussi 176 ou 376)" },
    { "number": 56, "orga": "Iran" },
    { "number": 256, "orga": "Iran" },
    { "number": 57, "orga": "Irlande" },
    { "number": 257, "orga": "Irlande" },
    { "number": 58, "orga": "Islande" },
    { "number": 258, "orga": "Islande" },
    { "number": 59, "orga": "Israël" },
    { "number": 259, "orga": "Israël" },
    { "number": 60, "orga": "Italie" },
    { "number": 260, "orga": "Italie" },
    { "number": 61, "orga": "Jamaïque" },
    { "number": 261, "orga": "Jamaïque" },
    { "number": 62, "orga": "Japon" },
    { "number": 262, "orga": "Japon" },
    { "number": 63, "orga": "Jordanie" },
    { "number": 263, "orga": "Jordanie" },
    { "number": 64, "orga": "Kenya" },
    { "number": 264, "orga": "Kenya" },
    { "number": 65, "orga": "Koweït" },
    { "number": 265, "orga": "Koweït" },
    { "number": 66, "orga": "Laos" },
    { "number": 266, "orga": "Laos" },
    { "number": 67, "orga": "Liban" },
    { "number": 267, "orga": "Liban" },
    { "number": 68, "orga": "Liberia" },
    { "number": 268, "orga": "Liberia" },
    { "number": 69, "orga": "Libye" },
    { "number": 269, "orga": "Libye" },
    { "number": 70, "orga": "Liechtenstein" },
    { "number": 270, "orga": "Liechtenstein" },
    { "number": 71, "orga": "Luxembourg" },
    { "number": 271, "orga": "Luxembourg" },
    { "number": 72, "orga": "Malaisie" },
    { "number": 272, "orga": "Malaisie" },
    { "number": 73, "orga": "Malawi" },
    { "number": 273, "orga": "Malawi" },
    { "number": 74, "orga": "Madagascar" },
    { "number": 274, "orga": "Madagascar" },
    { "number": 75, "orga": "Mali" },
    { "number": 275, "orga": "Mali" },
    { "number": 76, "orga": "Maroc" },
    { "number": 276, "orga": "Maroc" },
    { "number": 77, "orga": "Mauritanie" },
    { "number": 277, "orga": "Mauritanie" },
    { "number": 78, "orga": "Mexique" },
    { "number": 278, "orga": "Mexique" },
    { "number": 79, "orga": "Monaco" },
    { "number": 279, "orga": "Monaco" },
    { "number": 80, "orga": "Népal" },
    { "number": 280, "orga": "Népal" },
    { "number": 81, "orga": "Nicaragua" },
    { "number": 281, "orga": "Nicaragua" },
    { "number": 82, "orga": "Niger" },
    { "number": 282, "orga": "Niger" },
    { "number": 83, "orga": "Nigeria" },
    { "number": 283, "orga": "Nigeria" },
    { "number": 84, "orga": "Norvège" },
    { "number": 284, "orga": "Norvège" },
    { "number": 85, "orga": "Nouvelle-Zélande" },
    { "number": 285, "orga": "Nouvelle-Zélande" },
    { "number": 86, "orga": "Ouganda" },
    { "number": 286, "orga": "Ouganda" },
    { "number": 87, "orga": "Pakistan" },
    { "number": 287, "orga": "Pakistan" },
    { "number": 88, "orga": "Panama" },
    { "number": 288, "orga": "Panama" },
    { "number": 89, "orga": "Paraguay" },
    { "number": 289, "orga": "Paraguay" },
    { "number": 90, "orga": "Pays-Bas" },
    { "number": 290, "orga": "Pays-Bas" },
    { "number": 91, "orga": "Pérou" },
    { "number": 291, "orga": "Pérou" },
    { "number": 92, "orga": "Philippines" },
    { "number": 292, "orga": "Philippines" },
    { "number": 93, "orga": "Pologne" },
    { "number": 293, "orga": "Pologne" },
    { "number": 94, "orga": "Portugal" },
    { "number": 294, "orga": "Portugal" },
    { "number": 95, "orga": "ex-Rhodésie (obsolète)" },
    { "number": 295, "orga": "ex-Rhodésie (obsolète)" },
    { "number": 96, "orga": "Roumanie" },
    { "number": 296, "orga": "Roumanie" },
    { "number": 97, "orga": "Rwanda" },
    { "number": 297, "orga": "Rwanda" },
    { "number": 98, "orga": "Saint-Marin" },
    { "number": 298, "orga": "Saint-Marin" },
    { "number": 99, "orga": "Saint-Siège" },
    { "number": 299, "orga": "Saint-Siège" },
    { "number": 100, "orga": "Sénégal" },
    { "number": 300, "orga": "Sénégal" },
    { "number": 101, "orga": "Sierra Leone" },
    { "number": 301, "orga": "Sierra Leone" },
    { "number": 102, "orga": "Somalie" },
    { "number": 302, "orga": "Somalie" },
    { "number": 103, "orga": "Soudan" },
    { "number": 303, "orga": "Soudan" },
    { "number": 104, "orga": "Suède" },
    { "number": 304, "orga": "Suède" },
    { "number": 105, "orga": "Suisse" },
    { "number": 305, "orga": "Suisse" },
    { "number": 106, "orga": "Syrie" },
    { "number": 306, "orga": "Syrie" },
    { "number": 107, "orga": "Tanzanie" },
    { "number": 307, "orga": "Tanzanie" },
    { "number": 108, "orga": "Tchad" },
    { "number": 308, "orga": "Tchad" },
    { "number": 109, "orga": "ex-Tchécoslovaquie (obsolète)" },
    { "number": 309, "orga": "ex-Tchécoslovaquie (obsolète)" },
    { "number": 110, "orga": "Thaïlande" },
    { "number": 310, "orga": "Thaïlande" },
    { "number": 111, "orga": "Togo" },
    { "number": 311, "orga": "Togo" },
    { "number": 112, "orga": "Trinité-et-Tobago" },
    { "number": 312, "orga": "Trinité-et-Tobago" },
    { "number": 113, "orga": "Tunisie" },
    { "number": 313, "orga": "Tunisie" },
    { "number": 114, "orga": "Turquie" },
    { "number": 314, "orga": "Turquie" },
    { "number": 115, "orga": "Russie (Fédération de)" },
    { "number": 315, "orga": "Russie (Fédération de)" },
    { "number": 116, "orga": "Uruguay" },
    { "number": 316, "orga": "Uruguay" },
    { "number": 117, "orga": "Venezuela" },
    { "number": 317, "orga": "Venezuela" },
    { "number": 118, "orga": "Vietnam" },
    { "number": 318, "orga": "Vietnam" },
    { "number": 119, "orga": "Yémen" },
    { "number": 319, "orga": "Yémen" },
    { "number": 120, "orga": "Yougoslavie" },
    { "number": 320, "orga": "Yougoslavie" },
    { "number": 121, "orga": "Zambie" },
    { "number": 321, "orga": "Zambie" },
    { "number": 122, "orga": "Maurice" },
    { "number": 322, "orga": "Maurice" },
    { "number": 123, "orga": "Mongolie" },
    { "number": 323, "orga": "Mongolie" },
    { "number": 124, "orga": "ex-République Démocratique du Yémen (obsolète)" },
    { "number": 324, "orga": "ex-République Démocratique du Yémen (obsolète)" },
    { "number": 125, "orga": "Bangladesh" },
    { "number": 325, "orga": "Bangladesh" },
    { "number": 126, "orga": "Qatar" },
    { "number": 326, "orga": "Qatar" },
    { "number": 127, "orga": "Émirats arabes unis" },
    { "number": 327, "orga": "Émirats arabes unis" },
    { "number": 128, "orga": "ex-RDA (obsolète)" },
    { "number": 328, "orga": "ex-RDA (obsolète)" },
    { "number": 129, "orga": "Singapour" },
    { "number": 329, "orga": "Singapour" },
    { "number": 130, "orga": "Oman" },
    { "number": 330, "orga": "Oman" },
    { "number": 131, "orga": "Bahreïn" },
    { "number": 331, "orga": "Bahreïn" },
    { "number": 132, "orga": "Corée (République Démocratique) + 193 ou 393" },
    { "number": 332, "orga": "Corée (République Démocratique) + 193 ou 393" },
    { "number": 133, "orga": "Seychelles" },
    { "number": 333, "orga": "Seychelles" },
    { "number": 134, "orga": "Malte" },
    { "number": 334, "orga": "Malte" },
    { "number": 135, "orga": "Djibouti" },
    { "number": 335, "orga": "Djibouti" },
    { "number": 136, "orga": "Comores" },
    { "number": 336, "orga": "Comores" },
    { "number": 137, "orga": "Angola" },
    { "number": 337, "orga": "Angola" },
    { "number": 138, "orga": "Guinée Équatoriale" },
    { "number": 338, "orga": "Guinée Équatoriale" },
    { "number": 139, "orga": "Zimbabwe" },
    { "number": 339, "orga": "Zimbabwe" },
    { "number": 140, "orga": "Cap-Vert" },
    { "number": 340, "orga": "Cap-Vert" },
    { "number": 141, "orga": "Guinée-Bissau" },
    { "number": 341, "orga": "Guinée-Bissau" },
    { "number": 142, "orga": "Mozambique" },
    { "number": 342, "orga": "Mozambique" },
    { "number": 143, "orga": "Suriname" },
    { "number": 343, "orga": "Suriname" },
    { "number": 144, "orga": "Sainte-Lucie" },
    { "number": 344, "orga": "Sainte-Lucie" },
    { "number": 145, "orga": "Gambie" },
    { "number": 345, "orga": "Gambie" },
    { "number": 146, "orga": "Brunei" },
    { "number": 346, "orga": "Brunei" },
    { "number": 147, "orga": "Sao Tomé-et-Principe" },
    { "number": 347, "orga": "Sao Tomé-et-Principe" },
    { "number": 148, "orga": "Belize" },
    { "number": 348, "orga": "Belize" },
    { "number": 149, "orga": "Namibie" },
    { "number": 349, "orga": "Namibie" },
    { "number": 150, "orga": "Estonie" },
    { "number": 350, "orga": "Estonie" },
    { "number": 151, "orga": "Lettonie" },
    { "number": 351, "orga": "Lettonie" },
    { "number": 152, "orga": "Lituanie" },
    { "number": 352, "orga": "Lituanie" },
    { "number": 153, "orga": "Ukraine" },
    { "number": 353, "orga": "Ukraine" },
    { "number": 154, "orga": "Bahamas" },
    { "number": 354, "orga": "Bahamas" },
    { "number": 155, "orga": "Barbade" },
    { "number": 355, "orga": "Barbade" },
    { "number": 156, "orga": "Botswana" },
    { "number": 356, "orga": "Botswana" },
    { "number": 157, "orga": "Fidji" },
    { "number": 357, "orga": "Fidji" },
    { "number": 158, "orga": "Grenade" },
    { "number": 358, "orga": "Grenade" },
    { "number": 159, "orga": "Guyana" },
    { "number": 359, "orga": "Guyana" },
    { "number": 160, "orga": "Lesotho" },
    { "number": 360, "orga": "Lesotho" },
    { "number": 161, "orga": "Papouasie-Nouvelle-Guinée" },
    { "number": 361, "orga": "Papouasie-Nouvelle-Guinée" },
    { "number": 162, "orga": "Samoa" },
    { "number": 362, "orga": "Samoa" },
    { "number": 163, "orga": "Tonga" },
    { "number": 363, "orga": "Tonga" },
    { "number": 164, "orga": "Antigua-et-Barbuda" },
    { "number": 364, "orga": "Antigua-et-Barbuda" },
    { "number": 165, "orga": "Slovénie" },
    { "number": 365, "orga": "Slovénie" },
    { "number": 166, "orga": "Croatie" },
    { "number": 366, "orga": "Croatie" },
    { "number": 167, "orga": "Slovaquie" },
    { "number": 367, "orga": "Slovaquie" },
    { "number": 168, "orga": "République Tchèque" },
    { "number": 368, "orga": "République Tchèque" },
    { "number": 169, "orga": "Bosnie-Herzégovine" },
    { "number": 369, "orga": "Bosnie-Herzégovine" },
    { "number": 170, "orga": "Macédoine" },
    { "number": 370, "orga": "Macédoine" },
    { "number": 171, "orga": "Arménie" },
    { "number": 371, "orga": "Arménie" },
    { "number": 172, "orga": "Belarus" },
    { "number": 372, "orga": "Belarus" },
    { "number": 173, "orga": "Kazakhstan" },
    { "number": 373, "orga": "Kazakhstan" },
    { "number": 174, "orga": "Géorgie" },
    { "number": 374, "orga": "Géorgie" },
    { "number": 175, "orga": "Turkménistan" },
    { "number": 375, "orga": "Turkménistan" },
    { "number": 176, "orga": "Irak obsolète (ex Section des intérêts. Voir aussi 55 ou 255)" },
    { "number": 376, "orga": "Irak obsolète (ex Section des intérêts. Voir aussi 55 ou 255)" },
    { "number": 177, "orga": "Ouzbékistan" },
    { "number": 377, "orga": "Ouzbékistan" },
    { "number": 178, "orga": "Azerbaïdjan" },
    { "number": 378, "orga": "Azerbaïdjan" },
    { "number": 179, "orga": "Andorre" },
    { "number": 379, "orga": "Andorre" },
    { "number": 180, "orga": "Érythrée" },
    { "number": 380, "orga": "Érythrée" },
    { "number": 181, "orga": "Moldavie" },
    { "number": 381, "orga": "Moldavie" },
    { "number": 182, "orga": "Saint-Vincent-et-Grenadines" },
    { "number": 382, "orga": "Saint-Vincent-et-Grenadines" },
    { "number": 183, "orga": "Dominique" },
    { "number": 383, "orga": "Dominique" },
    { "number": 184, "orga": "Saint-Christophe-et-Niévès" },
    { "number": 384, "orga": "Saint-Christophe-et-Niévès" },
    { "number": 185, "orga": "Monténégro" },
    { "number": 385, "orga": "Monténégro" },
    { "number": 186, "orga": "Salomon" },
    { "number": 386, "orga": "Salomon" },
    { "number": 187, "orga": "Palaos" },
    { "number": 387, "orga": "Palaos" },
    { "number": 188, "orga": "Îles Cook" },
    { "number": 388, "orga": "Îles Cook" },
    { "number": 189, "orga": "Kirghizistan" },
    { "number": 389, "orga": "Kirghizistan" },
    { "number": 190, "orga": "Québec" },
    { "number": 191, "orga": "Cour Internationale de Justice" },
    { "number": 192, "orga": "?" },
    { "number": 193, "orga": "Corée (Rép. Démocr. - représentation commerciale)" },
    { "number": 194, "orga": "?" },
    { "number": 195, "orga": "Délégation permanente de l'Autorité palestinienne" },
    { "number": 196, "orga": "Taïwan (représentation commerciale)" },
    { "number": 197, "orga": "Kosovo" },
    { "number": 198, "orga": "Soudan du Sud" },
    { "number": 199, "orga": "Tadjikistan" },
    { "number": 401, "orga": "UNESCO : United Nations Educational Scientific and Cultural Organization (1945, Paris)" },
    { "number": 402, "orga": "OCDE : Organisation de Coopération et de Développement Économique (1960, Paris)" },
    { "number": 403, "orga": "OTAN : Organisation du Traité de l'Atlantique Nord (1949, Bruxelles)" },
    { "number": 404, "orga": "ELDO : European Launcher Development Organisation (1962) - Obsolète" },
    { "number": 405, "orga": "ESA : Agence Spatiale Européenne (1975, Paris) - ex ESRO : European Space Research Organisation" },
    { "number": 406, "orga": "CCNR : Commission Centrale de Navigation du Rhin (Strasbourg)" },
    { "number": 407, "orga": "OACI : Organisation d'Aviation Civile Internationale (1947, Montréal)" },
    { "number": 408, "orga": "BIRD : Banque Internationale pour la Reconstruction et le Développement (1945, Washington)" },
    { "number": 409, "orga": "FMI : Fonds Monétaire International (1945, Washington)" },
    { "number": 410, "orga": "UNICEF : Fonds des Nations unies pour l'enfance (1946, New York)" },
    { "number": 411, "orga": "UNIC : Centre d'Information des Nations Unies" },
    { "number": 412, "orga": "OIT : Organisation Internationale du Travail (1919, Genève)" },
    { "number": 413, "orga": "UEO : Union de l'Europe Occidentale (1948, Bruxelles)" },
    { "number": 414, "orga": "UNHCR : Haut Commissariat des Nations Unies pour les Réfugiés (1950, Genève)" },
    { "number": 415, "orga": "Union européenne (1993, Bruxelles) - ex-CEE (1957, Bruxelles)" },
    { "number": 416, "orga": "EURATOM : Communauté Européenne de l'Énergie Atomique CEEA (1958, Bruxelles)" },
    { "number": 417, "orga": "AFE : Agence Ferroviaire Européenne (2004, Valenciennes) — Anciennement CECA : Communauté Européenne du Charbon et de l'Acier de 1952 à 2002" },
    { "number": 418, "orga": "OEMPP : Organisation Européenne et Méditerranéenne pour la Protection des Plantes (1951)" },
    { "number": 419, "orga": "OIML : Organisation Internationale de Métrologie Légale (1955, Paris)" },
    { "number": 420, "orga": "Eurocontrol : Organisation européenne pour la sécurité de la navigation aérienne (1963, Bruxelles)" },
    { "number": 421, "orga": "OIVV : Organisation Internationale de la Vigne et du Vin (1958)" },
    { "number": 422, "orga": "BIE : Bureau International des Expositions (1928, Paris)" },
    { "number": 423, "orga": "BID : Banque Interaméricaine de Développement (1959, Washington)" },
    { "number": 424, "orga": "IIF : Institut International du Froid (1908, Paris)" },
    { "number": 425, "orga": "OIAC : Organisation Inter-Africaine du Café" },
    { "number": 426, "orga": "CIAA : Conférence internationale sur l'assurance africaine" },
    { "number": 427, "orga": "OAMCAF : Organisation Africaine et Malgache du Café (1960-2007)" },
    { "number": 428, "orga": "OFAJ : Office franco-allemand pour la jeunesse (1963, Paris-Berlin)" },
    { "number": 429, "orga": "CIPEC : Conseil Intergouvernemental des Pays Exportateurs de Cuivre (1967-1988, Lusaka)" },
    { "number": 430, "orga": "BCEAO : Banque Centrale des États de l'Afrique de l'Ouest (1962, Dakar)" },
    { "number": 431, "orga": "CERN : Organisation européenne pour la recherche nucléaire (1954, Genève)" },
    { "number": 432, "orga": "INTERPOL : Organisation Internationale de Police Criminelle (1923, Vienne ; 1946-56, Lyon)" },
    { "number": 433, "orga": "OIF : Organisation internationale de la francophonie, ex-ACCT : Agence de Coopération Culturelle et Technique, Agence de la Francophonie (1970, Paris)" },
    { "number": 434, "orga": "BIPM : Bureau International des Poids et Mesures (1875, Paris)" },
    { "number": 435, "orga": "LEBM : Laboratoire Européen de Biologie Moléculaire (1976, Grenoble)" },
    { "number": 436, "orga": "BADEA : Banque Arabe pour le Développement Économique en Afrique (1973, Khartoum)" },
    { "number": 437, "orga": "PNUE : Programme des Nations Unies pour l'Environnement (1972, Nairobi)" },
    { "number": 438, "orga": "OIE : Office International des Épizooties (1924, Paris)" },
    { "number": 439, "orga": "CIEPS : Centre international d’enregistrement des publications en série (1972, Paris)" },
    { "number": 440, "orga": "Eutelsat : Organisation européenne de télécommunications par satellite (1997, Paris)" },
    { "number": 441, "orga": "Union latine (1954-2012, Paris)" },
    { "number": 442, "orga": "Intelsat : Organisation internationale de télécommunications par satellite (1964, Washington)" },
    { "number": 443, "orga": "BEAC : Banque des États de l'Afrique Centrale (1972, Yaoundé)" },
    { "number": 444, "orga": "APF : Assemblée parlementaire de la Francophonie (1967, Paris)" },
    { "number": 445, "orga": "BERD : Banque Européenne pour la Reconstruction et le Développement (1991, Londres)" },
    { "number": 446, "orga": "OCVV : Office Communautaire des Variétés Végétales (1994, Angers)" },
    { "number": 447, "orga": "Secrétariat Général de la Francophonie" },
    { "number": 448, "orga": "CEDH : Cour Européenne des Droits de l'Homme (1959, Paris)" },
    { "number": 449, "orga": "Ligue des États arabes (1945, Le Caire)" },
    { "number": 450, "orga": "Bureau de projets de l'OMS (1992, Nancy)" },
    { "number": 451, "orga": "Commission européenne (1958, Bruxelles-Luxembourg)" },
    { "number": 452, "orga": "OCCAR : Organisation Conjointe de Coopération en matière d'Armement (1996, Bonn)" },
    { "number": 453, "orga": "IESUE : Institut d’Études de Sécurité de l’Union européenne (2001, Paris)" },
    { "number": 454, "orga": "ITER : Réacteur thermonucléaire expérimental international (2007, Cadarache)" },
    { "number": 455, "orga": "INIBAP : Réseau international pour l'amélioration de la production de la banane et de la banane plantain (1985, Montpellier)" },
    { "number": 456, "orga": "Agence du GNSS européen (2004, Prague)" },
    { "number": 457, "orga": "?" },
    { "number": 458, "orga": "CSSG : Centre de surveillance de la sécurité Galileo (Saint-Germain-en-Laye)" },
    { "number": 459, "orga": "CGIAR : Groupe consultatif pour la recherche agricole internationale (Montpellier)" },
    { "number": 460, "orga": "ABE : Autorité bancaire européenne (Paris La Défense)" },
    { "number": 500, "orga": "Hautes personnalités" },
    { "number": 501, "orga": "à 504 Conférence de la Paix au Vietnam (1973) - Obsolète" },
    { "number": 505, "orga": "Conférence Internationale de Coopération Économique - Obsolète" },
    { "number": 600, "orga": "Conseil de l'Europe (1949, Strasbourg)" },
    { "number": 700, "orga": "CIRC : Centre International de Recherche sur le Cancer (1965, Lyon)" },
    { "number": 800, "orga": "ex-OTAN en France (1965-1970) - Obsolète" }
  ];  

searchBar.addEventListener('keyup', (e) => {
    const searchString = e.target.value.toLowerCase();

    var filteredEntities = entities.filter((entity) => {
        return (
            entity.number == searchString ||
            entity.orga.toLowerCase().includes(searchString)
        );
    });
    
    if(filteredEntities.length == 0){
        filteredEntities = entities;
    }
    displayCharacters(filteredEntities);
    console.log(filteredEntities)
});

const displayCharacters = (filtered) => {
    const htmlString = filtered
        .map((entity) => {
            return `
            <li class="entity">
                <h2>${entity.orga}</h2>
                <p>Numéro : ${entity.number}</p>
            </li>
        `;
        })
        .join('');
        
    entitiesList.innerHTML = htmlString;
};

displayCharacters(entities)
